### ISSUE TITLE
Close button isn't skinned properly

### ISSUE THREAD

**Issue by Meivyn** [Klixxx/ElvUI_AdiBags#1]
Basically, ElvUI's skin function is like:
```lua
function S:HandleCloseButton(f, point)
	f:StripTextures()

	if not f.Texture then
		f.Texture = f:CreateTexture(nil, 'OVERLAY')
		f.Texture:Point("CENTER")
		f.Texture:SetTexture(E.Media.Textures.Close)
		f.Texture:Size(12, 12)
		f:HookScript('OnEnter', handleCloseButtonOnEnter)
		f:HookScript('OnLeave', handleCloseButtonOnLeave)
		f:SetHitRectInsets(6, 6, 7, 7)
	end

	if point then
		f:Point("TOPRIGHT", point, "TOPRIGHT", 2, 2)
	end
end
```
And to skin it, you do:
```lua
ElvUI[1]:GetModule("Skins"):HandleCloseButton(self.CloseButton) -- ElvUI Mod!
```
And this is just running ``f:StripTextures()`` because ``f.Texture`` already exists, but I can't tell where it's handled, maybe when you are skinning the whole frame.

To fix it, just remove that line from the code.

**Comment by Meivyn** [comment]
Nevermind, it was an issue created with my personal attempt to skin AdiBags which conflicted with yours.

**Comment by Klixxx** [comment]
Awesome!
Im glad it worked, ye that line is the only thing you need to write to skin the closebutton, elvui api will take care of the rest :)
