### ISSUE TITLE
Addon simply doesn't work

### ISSUE THREAD

**Issue by loki266** [Klixxx/ElvUI_AdiBags#19]
When I install this addon, nothing happens when I try to open the bags. To be more specific, I can hear the sound of the bag opening, but it won't show in-game.

**Comment by shinlang** [comment]
Fixed it for me by opening the AdiBags options via _/adibags_ and enabling the addon for backpack and bank, both were apparently disabled.

**Comment by Klixxx** [comment]
Ill set it to default
