### ISSUE TITLE
Open space in height bag

### ISSUE THREAD

**Issue by PepanVrban** [Klixxx/ElvUI_AdiBags#23]
Hi,
I have little problem with how to adjust the width and height of the bag and we leave an empty space on the right.
It can be adjusted somehow so that this free space is not displayed.

![AdiBags 1](https://user-images.githubusercontent.com/75945130/102018207-1bf90900-3d6c-11eb-8d18-e87fd4ed8eb2.JPG)
![AdiBags 2](https://user-images.githubusercontent.com/75945130/102018209-1d2a3600-3d6c-11eb-884c-494c0ea2f787.JPG)

PS: best bag addon :-))

**Comment by Klixxx** [comment]
Reduce the amount of currency showing, you have all showing :)

**Comment by PepanVrban** [comment]
WOW.

Thank you so much! :D

**Comment by SpareSimian** [comment]
I love AdiBags for bag contents but I find I like the currency display of Titan Panel's currency module best for watching my money.
