### ISSUE TITLE
Item upgrade icon Pawn broken again.

### ISSUE THREAD

**Issue by Falx** [Klixxx/ElvUI_AdiBags#25]
The item upgrade arrow of Pawn is not displayed. It can be fixed  in `widgets/ItemButton.lua`

```lua
function buttonProto:UpdateUpgradeIcon()
	self.UpgradeIcon:SetShown(IsContainerItemAnUpgrade(self.bag, self.slot) or false)
end
```
Should be:

```lua
function buttonProto:UpdateUpgradeIcon()
	if IsAddOnLoaded('Pawn') then itemIsUpgrade = _G.PawnIsContainerItemAnUpgrade(self.bag, self.slot) end
	if itemIsUpgrade == nil then itemIsUpgrade = _G.IsContainerItemAnUpgrade(self.bag, self.slot) end
	self.UpgradeIcon:SetShown( itemIsUpgrade or false)
end
```

Could you make this fix please?

**Comment by Klixxx** [comment]
Make a pull request :)

**Comment by Falx** [comment]
Gladly, I was starting to, but then saw that commit 47ced69652263ba04336b6c218fa3510c79a0e01 already fixed it (on the development branch). Any idea when this gets released?

**Comment by Klixxx** [comment]
Ill make a new release today after work :)
