### ISSUE TITLE
Adibags + BenikUI Style function bug

### ISSUE THREAD

**Issue by allethargic** [Klixxx/ElvUI_AdiBags#29]
In coming update of BenikUI dev will fix bug with Kaliel Tracker, which required changing of basic Style function. But now it's bugged with your addon. It looks like that with BenikUI enabled:
![unknown](https://user-images.githubusercontent.com/68805541/111777502-70a8a480-88c4-11eb-9b6d-6471ad6840e0.png)
Benik told me how to fix it:
> Adibags\widgets\BagSlots.lua, line 439 self:Style("Inside") change it to self:BuiStyle("Inside")
and Adibags\widgets\ContainerFrame.lua, line 659, do the same

Hope you will be able to fix it so it works for BenikUI users and default ElvUI users.

**Comment by Bauxite** [comment]
Can confirm with the recent update of BenikUI to 4.05, Adibags is broken - an error is thrown on login and you are unable to open the bags.  The changes above resolved the issue, thank you for providing.

**Comment by Klixxx** [comment]
Fixed in build 17
