### ISSUE TITLE
TBC Classic Support

### ISSUE THREAD

**Issue by Sl0th-KungFu** [Klixxx/ElvUI_AdiBags#31]
Since the pre patch the addon is not working. On the official AdiBags Github is already a pull request.
https://github.com/AdiAddons/AdiBags/pull/566

There is also an issue on the official AdiBags Github regarding the support of TBC.
https://github.com/AdiAddons/AdiBags/issues/580

**Comment by Klixxx** [comment]
I have pushed a release for TBC classic at curseforge

https://www.curseforge.com/wow/addons/elvui-adibags/files/3315512
