### ISSUE TITLE
Error in AdiBags: Interface\AddOns\AdiBags\widgets\ItemButton.lua:340: attempt to index field 'ScrappingMachineFrame' (a nil value) -- details: [Error 000002C0D0628E90] 

### ISSUE THREAD

**Issue by Phred88** [Klixxx/ElvUI_AdiBags#4]
Hey, I've installed your addon but I keep seeing the following message every time I open my bags:

Error in AdiBags: Interface\AddOns\AdiBags\widgets\ItemButton.lua:340: attempt to index field 'ScrappingMachineFrame' (a nil value) -- details: [Error 000002C0D0628E90] 

When I click on the error code I get this:
[14:14] Interface\AddOns\AdiBags\widgets\ItemButton.lua:340: attempt to index field 'ScrappingMachineFrame' (a nil value) 
[14:14] Interface\AddOns\AdiBags\widgets\ItemButton.lua:340: in function `Update'
Interface\AddOns\AdiBags\widgets\ItemButton.lua:305: in function `FullUpdate'
Interface\AddOns\AdiBags\widgets\ItemButton.lua:270: in function <Interface\AddOns\AdiBags\widgets\ItemButton.lua:258>
[C]: in function `Show'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:978: in function `PrepareSections'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1084: in function `FullUpdate'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:579: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:565>
[C]: ?
Interface\AddOns\AdiBags\core\Utility.lua:89: in function <Interface\AddOns\AdiBags\core\Utility.lua:81>
Interface\AddOns\AdiBags\widgets\LayeredRegion.lua:119: in function <Interface\AddOns\AdiBags\widgets\LayeredRegion.lua:108> 
[14:14] self = AdiBagsItemButton156 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
 icon = AdiBagsItemButton156IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 ScrapIcon = <unnamed> {
 }
 pushed = <unnamed> {
 }
 UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1376
 ExtendedOverlay = <unnamed> {
 }
 count = 1
 section = AdiBagsSection17 {
 }
 filterName = "Equipment"
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 texture = 2280685
 UpgradeIcon = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 itemLink = "[Vestments of the Afterlife]"
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton156Cooldown {
 }
 bagFamily = 0
 itemId = 165498
 BagStaticBottom = <unnamed> {
 }
 glossTex = true
 PixelSnapDisabled = true
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 bag = 3
 acquired = true
 hover = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 SetBackdropColor = <function> defined =[C]:-1
 IconTexture = AdiBagsItemButton156IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 slot = 23
 template = "Default"
 NormalTexture = AdiBagsItemButton156NormalTexture {
 }
 Stock = AdiBagsItemButton156Stock {
 }
 IconQuestTexture = AdiBagsItemButton156IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton156Count {
 }
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 pixelBorders = <table> {
 }
 searchOverlay = AdiBagsItemButton156SearchOverlay {
 }
}
icon = AdiBagsItemButton156IconTexture {
 0 = <userdata>
 PixelSnapDisabled = true
}
tag = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = 2280685
(*temporary) = 1
(*temporary) = "attempt to index field 'ScrappingMachineFrame' (a nil value)"
unpack = <function> defined =[C]:-1
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:173
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined

Good luck with this :)

**Comment by Klixxx** [comment]
Can you please try and download the latest development version, think i have fixed it!
Please delete old adibags folders before dragging these new folers inside your addons folders

https://github.com/Klixxx/ElvUI_AdiBagsI/archive/development.zip

**Comment by Phred88** [comment]
The error is gone but now each bag is seperated and no longer all in-one-bag?

**Comment by Phred88** [comment]
Ok error is gone, Thanks :)

**Comment by Klixxx** [comment]
perfect, ill push an update!
