### ISSUE TITLE
Item Upgrade Icon (Pawn)

### ISSUE THREAD

**Issue by Beet4** [Klixxx/ElvUI_AdiBags#5]
Hi!

In the standard AdiBags the item upgrade icon worked (UpdateUpgradeIcon()) flawlessly. I think it's available as standard by Blizzard by using itemlevel as well. I have Pawn installed which should alter the behaviour to show the icon if Pawn thinks it's an upgrade. In this version the icon does not appear at all.

Edit: I think the functions name is IsContainerItemAnUpgrade

**Comment by Klixxx** [comment]
Havent touched that, the function is still there, and you sure it works in the original aidbags addon? can you show me some SS please.

**Comment by Beet4** [comment]
Tested now and works in original AdiBags.

Original AdiBags:
https://i.imgur.com/F6ENWU5.jpg
Elvui edit:
https://i.imgur.com/1Pge0yZ.jpg
Pawn settings:
https://i.imgur.com/fL01sjA.jpg

**Comment by Klixxx** [comment]
I see, i cant seem to locate the issue, ill have to dig deeper

**Comment by Beet4** [comment]
> I see, i cant seem to locate the issue, ill have to dig deeper

Hi! Any progress on this issue? :)

**Comment by Aioncheg** [comment]
Just remove or comment line 
`local IsContainerItemAnUpgrade = _G.IsContainerItemAnUpgrade`
in widgets/ItemButton.lua

**Comment by Beet4** [comment]
> Just remove or comment line
> `local IsContainerItemAnUpgrade = _G.IsContainerItemAnUpgrade`
> in widgets/ItemButton.lua

You are a ******* LEGEND! Thx!

And thx @Klixxx for the quick release of the fix! :D
