### ISSUE TITLE
Frame scaling sometimes messes up item quality borders

### ISSUE THREAD

**Issue by ririshi** [Klixxx/ElvUI_AdiBags#6]
The item quality borders (green, blue, purple, etc) are sometimes not fully visible when scaling the bag frame up and down. For example, on my 1440p screen, setting the scale to 90% removes the top border of the first row of items in the inventory as you can see in the screenshow below. I'm running ElvUI Classic 1.08 with ElvUI Adibags 0.0.5. My ElvUI UI Scale is set to 0.6 if that matters at all.

![image](https://user-images.githubusercontent.com/8461226/64952901-ce989e00-d881-11e9-8065-6b87002fa0d3.png)

**Comment by Klixxx** [comment]
I can only recommend you to try and find a bag scale and ui scale that works together, its a scaling issue and has not been working for months now, since blizzard removed some stuff.
So this cant be fixed sadly.
