### ISSUE TITLE
Getting Errors, bags wont even open.

### ISSUE THREAD

**Issue by Comgamer7** [Klixxx/ElvUI_AdiBags#7]
Date: 2019-10-10 13:44:12
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\OO.lua line 54:
   CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
Debug:
   AdiBags\core\Utility.lua:77:
      AdiBags\core\Utility.lua:73
   (tail call): ?
   AdiBags\core\OO.lua:60:
      AdiBags\core\OO.lua:52
   (tail call): ?
   (tail call): ?
   AdiBags\core\Bags.lua:129: GetFrame()
   AdiBags\core\Bags.lua:83: Open()
   AdiBags\core\Hooks.lua:112:
      AdiBags\core\Hooks.lua:109
   (tail call): ?
   (tail call): ?
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.31
  AdiBags, vDEV
  Atlas, vv1.45.01.11302
  AtlasArena, vv1.07.04
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasBurningCrusade, vv1.45.00
  AtlasCataclysm, vv1.45.00
  AtlasClassOrderHalls, vv1.45.00
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLegion, vv1.45.01
  AtlasMistsofPandaria, vv1.45.00
  AtlasOutdoorRaids, vv1.45.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.45.00.11302.00
  AtlasWarlordsofDraenor, vv1.45.00
  AtlasWorldEvents, vv3.26
  AtlasWrathoftheLichKing, vv1.45.00
  AtlasMajorCitiesEnhanced, vv1.16
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ConRO, v8.2.17
  ConRODemonHunter, v8.2.2
  DBMCore, v1.13.14
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v11.24
  ElvUIGennUI, v2.23
  ElvUISLE, v3.59
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GarrisonCommanderBroker, v3.2.2 1.1.0
  GTFO, v4.50.1
  HideObjectives, v1.1.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v8.2.11
  NPCScan, v8.0.1.13
  Pawn, v2.3.7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v3.6.14
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv80205-1.0.7
  WoWPro, v8.2.5-A1
  WoWProAchievements, v8.2.5-A1
  WoWProDailies, v8.2.5-A1
  WoWProLeveling, v8.2.5-A1
  WoWProProfession, v8.2.5-A1
  WoWProWorldEvents, v8.2.5-A1
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=6f2)

**Comment by Comgamer7** [comment]
Date: 2019-10-10 13:44:12
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Bags.lua line 130:
   attempt to index field 'CloseButton' (a nil value)
Debug:
   [C]: ?
   AdiBags\core\Bags.lua:130: GetFrame()
   AdiBags\core\Bags.lua:83: Open()
   AdiBags\core\Hooks.lua:112:
      AdiBags\core\Hooks.lua:109
   (tail call): ?
   (tail call): ?
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.31
  AdiBags, vDEV
  Atlas, vv1.45.01.11302
  AtlasArena, vv1.07.04
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasBurningCrusade, vv1.45.00
  AtlasCataclysm, vv1.45.00
  AtlasClassOrderHalls, vv1.45.00
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLegion, vv1.45.01
  AtlasMistsofPandaria, vv1.45.00
  AtlasOutdoorRaids, vv1.45.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.45.00.11302.00
  AtlasWarlordsofDraenor, vv1.45.00
  AtlasWorldEvents, vv3.26
  AtlasWrathoftheLichKing, vv1.45.00
  AtlasMajorCitiesEnhanced, vv1.16
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ConRO, v8.2.17
  ConRODemonHunter, v8.2.2
  DBMCore, v1.13.14
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v11.24
  ElvUIGennUI, v2.23
  ElvUISLE, v3.59
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GarrisonCommanderBroker, v3.2.2 1.1.0
  GTFO, v4.50.1
  HideObjectives, v1.1.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v8.2.11
  NPCScan, v8.0.1.13
  Pawn, v2.3.7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v3.6.14
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv80205-1.0.7
  WoWPro, v8.2.5-A1
  WoWProAchievements, v8.2.5-A1
  WoWProDailies, v8.2.5-A1
  WoWProLeveling, v8.2.5-A1
  WoWProProfession, v8.2.5-A1
  WoWProWorldEvents, v8.2.5-A1
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=6f2)

**Comment by Comgamer7** [comment]
Date: 2019-10-10 13:46:26
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 479:
   attempt to index field 'Title' (a nil value)
Debug:
   AdiBags\core\Utility.lua:77:
      AdiBags\core\Utility.lua:73
   (tail call): ?
   AdiBags\widgets\LayeredRegion.lua:119:
      AdiBags\widgets\LayeredRegion.lua:108
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.31
  AdiBags, vDEV
  Atlas, vv1.45.01.11302
  AtlasArena, vv1.07.04
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasBurningCrusade, vv1.45.00
  AtlasCataclysm, vv1.45.00
  AtlasClassOrderHalls, vv1.45.00
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLegion, vv1.45.01
  AtlasMistsofPandaria, vv1.45.00
  AtlasOutdoorRaids, vv1.45.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.45.00.11302.00
  AtlasWarlordsofDraenor, vv1.45.00
  AtlasWorldEvents, vv3.26
  AtlasWrathoftheLichKing, vv1.45.00
  AtlasMajorCitiesEnhanced, vv1.16
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ConRO, v8.2.17
  ConRODemonHunter, v8.2.2
  DBMCore, v1.13.14
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v11.24
  ElvUIGennUI, v2.23
  ElvUISLE, v3.59
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GarrisonCommanderBroker, v3.2.2 1.1.0
  GTFO, v4.50.1
  HideObjectives, v1.1.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v8.2.11
  NPCScan, v8.0.1.13
  Pawn, v2.3.7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v3.6.14
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv80205-1.0.7
  WoWPro, v8.2.5-A1
  WoWProAchievements, v8.2.5-A1
  WoWProDailies, v8.2.5-A1
  WoWProLeveling, v8.2.5-A1
  WoWProProfession, v8.2.5-A1
  WoWProWorldEvents, v8.2.5-A1
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=6f2)

**Comment by Klixxx** [comment]
I need the very first error, and please test with only elvui and the elvui Adibags version

**Comment by Comgamer7** [comment]
This is only with it, it doesnt show up in addons as elvuiadibags

**Comment by Comgamer7** [comment]
I think the problem is that the twitch app is downloading a classic version to use for retail. I will check it tommorow

**Comment by Klixxx** [comment]
Well if thats the case thats why you have errors, please report back if you have the wrong version
